# Generated by Django 4.0 on 2022-03-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพื่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่ย่อย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพื่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'หมวดหมู่ย่อย',
                'verbose_name_plural': 'หมวดหมู่ย่อย',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('quantity', models.IntegerField(verbose_name='จำนวนสินค้า')),
                ('price', models.FloatField(blank=True, max_length=4, null=True, verbose_name='ราคา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('category', models.ManyToManyField(to='product.SubCategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
    ]
